"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Shapes_1 = require("./Shapes");
const Circle_1 = require("./Circle");
const Rectangle_1 = require("./Rectangle");
let shape = new Shapes_1.Shape(10, 20);
let circle = new Circle_1.Circle(5, 4, 36);
let rectangle = new Rectangle_1.Rectangle(0, 0, 8, 4);
console.log(rectangle.getInfo());
console.log(circle.getInfo());
console.log(shape.getInfo());
